"""NotoSansKR-VF.ttf -> wght400 static -> KS X 1001 subset -> base64 JS module."""
import base64, io, os, sys
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from fontTools import subset

SRC = r"C:\Windows\Fonts\NotoSansKR-VF.ttf"
OUT_DIR = sys.argv[1]
WITH_HANJA = "--hanja" in sys.argv

# --- 1. KS X 1001 repertoire ---------------------------------------------
# Python's "euc-kr" codec is really CP949, which also covers the 8,822 extra
# Unified Hangul syllables. Keep only the two-byte KS X 1001 range
# (lead and trail both 0xA1-0xFE) so the subset stays classroom-sized.
ks = set()
for cp in range(0x20, 0x10000):
    ch = chr(cp)
    try:
        enc = ch.encode("euc-kr")
    except (UnicodeEncodeError, UnicodeError):
        continue
    if len(enc) == 1:                       # plain ASCII
        ks.add(cp)
        continue
    if len(enc) != 2 or not (0xA1 <= enc[0] <= 0xFE and 0xA1 <= enc[1] <= 0xFE):
        continue                            # CP949 extension / 8-byte fallback
    ks.add(cp)

if "--all-hangul" in sys.argv:
    ks |= set(range(0xAC00, 0xD7A4))
else:
    # KS X 1001's 2,350 syllables cover modern Korean almost completely; the
    # residual gaps are loanword transliterations a travel plan can plausibly
    # hit (똠얌꿍, 쌤, 팟…). Patching them in costs a few KB, whereas the full
    # 11,172-syllable build triples the file (see --all-hangul).
    ks |= {ord(c) for c in "똠뙤뽁뿅쀼썅쏵쫑쨈쨍쭙뻑뼝삣쌩쎈쏠쭐찡뀰뀄땋"}

hanja = {c for c in ks if 0x4E00 <= c <= 0x9FFF}
if not WITH_HANJA:
    ks -= hanja

# ASCII + Latin-1 + typographic extras the PDF actually prints
extras = set(range(0x20, 0x7F)) | set(range(0xA0, 0x100))
extras |= {0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2026,
           0x20A9, 0x20AC, 0x2192, 0x2190, 0x2191, 0x2193, 0x203B,
           0x2103, 0x00B7, 0x30FB, 0xFF5E, 0x2015}
extras |= set(range(0x2460, 0x2474))   # (1)~(20) circled numbers
extras |= set(range(0x3131, 0x3164))   # compatibility jamo
ks |= extras

print(f"[font] codepoints: {len(ks)} (hanja={'in' if WITH_HANJA else 'out'})")

# --- 2. variable -> static wght 400 --------------------------------------
font = TTFont(SRC)
font = instancer.instantiateVariableFont(font, {"wght": 400}, inplace=True,
                                         updateFontNames=False)

# --- 3. subset ------------------------------------------------------------
opts = subset.Options()
opts.layout_features = []          # jsPDF does no shaping; drop GSUB/GPOS
opts.name_IDs = [1, 2, 3, 4, 6]
opts.name_legacy = True
opts.notdef_outline = True
opts.recalc_bounds = True
opts.drop_tables += ["DSIG"]
opts.hinting = False
opts.desubroutinize = True
opts.glyph_names = False

subsetter = subset.Subsetter(options=opts)
subsetter.populate(unicodes=ks)
subsetter.subset(font)

font["name"].setName("Noto Sans KR Subset", 1, 3, 1, 0x409)
font["name"].setName("NotoSansKR-Regular-Subset", 4, 3, 1, 0x409)

buf = io.BytesIO()
font.save(buf)
ttf = buf.getvalue()
print(f"[font] ttf bytes: {len(ttf):,}")

os.makedirs(os.path.join(OUT_DIR, "fonts"), exist_ok=True)
with open(os.path.join(OUT_DIR, "fonts", "NotoSansKR-Regular.ttf"), "wb") as f:
    f.write(ttf)

b64 = base64.b64encode(ttf).decode("ascii")
lines = [b64[i:i + 120] for i in range(0, len(b64), 120)]
js_path = os.path.join(OUT_DIR, "fonts", "NotoSansKR-Regular.js")
with open(js_path, "w", encoding="utf-8", newline="\n") as f:
    f.write("// Noto Sans KR (SIL Open Font License 1.1) - wght 400 instance,\n")
    f.write("// KS X 1001 subset. jsPDF VFS embedding. Generated by tools/subset_font.py\n")
    f.write("export const NOTO_SANS_KR_BASE64 =\n")
    f.write("\n".join(f'  "{ln}" +' for ln in lines[:-1]))
    f.write("\n" if len(lines) > 1 else "")
    f.write(f'  "{lines[-1]}";\n')
print(f"[font] base64 chars: {len(b64):,} -> {js_path}")
